baseURL = 'https://kkbt0.github.io/Somnia/'
languageCode = 'zh-CN'
hasCJKLanguage = true
title = 'Somnia'
theme = '../..'


copyright = '© 2026 恐咖兵糖.'
# 是否使用 robots.txt
enableRobotsTXT = true
# 网站地图配置
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5
# Permalinks 配置
[Permalinks]
# posts = ":year/:month/:filename"
posts = "/posts/:slug"


[params]
description = ''
# Posts Tags Categories 配置页数
[params.limit]
blogPosts = 5 # /posts/ 每页左侧文章数
blogCategories = 10 # /posts/ 右侧分类数
blogTags = 50 # /posts/ 右侧标签数
categoriesPosts = 5 # /categories/xxx/ 每页文章数
tagsPosts = 5 # /tags/xxx/ 每页文章数
archivesPosts = 50 # 归档每页文章数

# Homepage 配置
# 作者配置
[params.author]
name = "恐咖兵糖"
email = "0@ftls.xyz"
link = "https://www.ftls.xyz"
avatar = "https://ftls.xyz/img/avatar.webp"
gravatarEmail = ""
location = 'China'
github = 'https://github.com/kkbt0'
bio = '浮生若梦 为欢几何'
about = ''

[params.homepage]
# homepage 配置
posts = 5 # 主页显示的文章数量
quote = true # 是否在主页显示一言

[params.education]
heading = 'Lorem ipsum.'
subheading = 'Lorem ipsum dolor sit amet, vidit suscipit at mei.'
date = 'August 2021 - July 2025'
url = '#'

[[params.websites]]
name = 'Columbina'
description = 'Columbina Hyposelenia'
url = 'https://example.org'
image = '/Somnia/images/default.webp'
[[params.websites]]
name = 'heading'
description = 'subheading'
url = 'https://example.org'
image = '/Somnia/images/default.webp'

[params.certifications]
heading = 'Lorem ipsum.'
subheading = 'Lorem ipsum dolor sit amet, vidit suscipit at mei.'
date = 'August 2021 - July 2025'
url = '#'

[[params.skills]]
title = 'Languages'
items = ['HTML5', 'CSS3', 'Javascript', 'Typescript', 'Golang', 'Rust', 'Python', 'C', 'C++','Lua']
[[params.skills]]
title = 'Frontend'
items = ['Alpinejs','Unocss']
[[params.skills]]
title = 'Backend'
items = ['Golang', 'Rust', 'Python']

[params.header]
[[params.header.menu]]
title = 'Blog'
link = 'posts'
[[params.header.menu]]
title = 'Docs'
link = 'docs'
[[params.header.menu]]
title = 'Projects'
link = 'projects'
[[params.header.menu]]
title = 'Links'
link = 'links'
[[params.header.menu]]
title = 'About'
link = 'about'

[params.footer]
powered = true
[params.footer.icp]
title = 'Moe ICP 114514'
link = 'https://icp.gov.moe/?keyword=114514'

[params.content]
blogPageSize = 8

[params.social]
github = 'https://github.com/'

[params.features]
search = true
